### ISSUE TITLE
Question regarding built-in intents

### ISSUE THREAD

**Issue by beowulf127** [pycontribs/django-alexa#26]
Thanks for putting together this library, it looks like it will be a real time saver!

I'm a noob with Alexa, but it seems like the example is not implementing the built-in intents properly.  This could be a complete oversight on my part of course, but I thought the built-in intents were supposed to be defined as "AMAZON.HelpIntent", for example, in the intent schema.  However, in the the example you have, you define the HelpIntent as "HelpIntent".  Is this intentional?  

I thought it might be because of the alexa.py file function names would be awkward otherwise.  However, this seems to then override the built-in intent utterances that Amazon provides.  Thanks for your help!

**Comment by rocktavious** [comment]
Yes, the Amazon documentation seemed to be off in describing the default intents.  So after playing with the library and then putting it into use i ended up realizing this and so as you see, it should work, it just doesn't match was Amazon's documentation says sadly. :(
