### ISSUE TITLE
how install and use.

### ISSUE THREAD

**Issue by yogeshmoradiya121** [pycontribs/django-alexa#36]
hey guys i'm new for python django. can any one help how to integrate this library with django

i have install it and when i place url(r'^', include('django_alexa.urls')) in  urls.py it shows error.

**Comment by briancaffey** [comment]
@yogeshmoradiya121 what error does it show? can you share the error message here?

**Comment by lingster** [comment]
what version of django has been installed? If it's >= 2.0 then you may try to replace the url with the following: 
    path('', include('django_alexa.urls')),

**Comment by lingster** [comment]
closing this issue as no response received
